services:
  axon-server:
    image: axoniq/axonserver:2025.2.5-nonroot
    environment:
      # DCB対応のContextを手動でしなくてもよくなる
      axoniq.axonserver.standalone-dcb: true
      axoniq_axonserver_hostname: axon-server
      axoniq_axonserver_devmode_enabled: true
    volumes:
      - momiji-axonserver-data:/axonserver/data
      - momiji-axonserver-events:/axonserver/events
    ports:
      - 8024:8024
      - 8124:8124
      - 8224:8224
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8024/actuator/health"]
      interval: 2s
      timeout: 2s
      retries: 30
      start_period: 5s

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: passw0rd
      MYSQL_DATABASE: momiji
    ports:
      - "3336:3306"
    volumes:
      - momiji-mysql-data:/var/lib/mysql

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: start-dev --import-realm
    environment:
      KC_DB: dev-mem
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./keycloak/momiji-realm.json:/opt/keycloak/data/import/momiji-realm.json:ro
    ports:
      - "8085:8080"

volumes:
  momiji-mysql-data:
  momiji-axonserver-data:
  momiji-axonserver-events: