spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 原則 DB接続情報は環境変数から取得する。これは設定忘れを防止するためである。
    # 例外としてローカル開発時のみ app-local.yaml で上書きされるようにしている。
    url: jdbc:mysql://${SPRING_DATASOURCE_HOST}:${SPRING_DATASOURCE_PORT}/${SPRING_DATASOURCE_DATABASE}?createDatabaseIfNotExist=true
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
