# ローカル / テスト / 本番環境での利用を想定
management:
  otlp:
    metrics:
      export:
        url: ${OTLP_METRICS_URL}
        # メトリクスを Prometheus にプッシュする間隔
        step: 10s
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: ${OTLP_TRACES_ENDPOINT}
  tracing:
    sampling:
      # トレーシングの頻度を制御。１.0 なら 100% サンプリング、0.1 なら 10% のサンプリング。
      probability: ${TRACE_SAMPLING_PROBABILITY}
