spring:
  # docker compose の起動はTaskfile側で制御するため、Spring Bootの自動起動はoff
  docker-compose-enabled: false
  profiles:
    active: local
    group:
      integration-test:
        - app-common
        # IDP / Mail / JwtDecoder / OidcUserInfoFetcher は @MockkBean で置き換えるため、
        # 本物の bean を作る idp-* / mail-* profile は外す。 これにより Keycloak / MailHog
        # の TestContainer を起動する必要もなくなる。
        - app-integration-test
      local:
        - app-common
        - datastore-mysql
        - idp-keycloak
        - mail-smtp
        # app-local は最後に置く。
        # 環境変数をローカル開発用の具体値で上書きさせたいため。
        - app-local
      test:
        - app-common
        - app-test
        - datastore-mysql
        - idp-cognito
        - mail-smtp
      prod:
        - app-common
        - app-prod
        - datastore-mysql
        - idp-cognito
        - mail-smtp
